Metadata:
  Author: "Andrea Santana López"
  Title: "Cloud Computing First practice"
  version: "1.0.0"
  Purpose: "It is designing simple app in AWS"

# Recursos para la implementación
Resources:
          AppHosted:
                       Type: AWS::EC2::Instance
                       Properties:
                                  # Necesaria para establecer todas las zonas
                                  AvailabilityZone: 
                                  #Condiciones de Cpu son necesarias para el tipo de instancia
                                  CpuOptions:         
                                  #Duda de poner estos dos
                                  HostId: 
                                  ImageId: 
                                  # Establece el tipo de instancia que necesito
                                  InstanceType: 
                                  #Para conectarse a la instancia
                                  KeyName: 
                                  #Para usar una  plantilla
                                  LaunchTemplate: 
                                  #Para definir las interfaces de red
                                  NetworkInterfaces: 
                                  #En duda
                                  PrivateIpAddress: 
                                  #En duda
                                  RamdiskId: 
                                  #Si utilizaramos otra VPC tendriamos que usar este
                                  SecurityGroupIds: 
                                  #Para configurar los grupos de seguridad
                                  SecurityGroups: 
                                  #Duda
                                  SubnetId: 
                                  #Para establecer las etiquetas
                                  Tags:
                                  #Duda
                                  UserData: String
          
        
